;run=../demos/demo.ls
workpath=.\demos\
;console=true
fps=30
debug=false
#window backcolor
;backcolor=#555
[font]
;font=terminus-18n.bdf
;font=gohufont-14.bdf
;font=spleen-12x24.bdf
;font=spleen-8x16.bdf
;font=9x18.bdf
;size=18

;font=roboto-regular.ttf
;font=dina-10.bdf
;font=twelvebyseven-16.bdf
;font=ComputerPixel-7-8.bdf
;font=terminus.ttf
;font=DejaVuSansMono.ttf

[show]
fps=true
#show console
;console=false
;window=true
#show log output
log=false